# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "messages.Repository" do
    optional :name, :string, 1
    optional :description, :string, 2
    optional :starts, :int64, 3
    optional :code_frequency, :float, 4
    map :language_contributions, :string, :int32, 5
  end
  add_message "messages.EnrollmentResponse" do
    optional :ack, :bool, 1
  end
end

module Messages
  Repository = Google::Protobuf::DescriptorPool.generated_pool.lookup("messages.Repository").msgclass
  EnrollmentResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("messages.EnrollmentResponse").msgclass
end
